CREATE DATABASE QUANLYTS
GO

USE QUANLYTS
GO


CREATE TABLE TABLE_DRINK(
	ID_TABLE INT IDENTITY PRIMARY KEY,
	NAME_TABLE NVARCHAR(100) NOT NULL,
	STATUS NVARCHAR(100) NOT NULL DEFAULT N'Trống'			-- 0 : TRỐNG - 1: CÓ NGƯỜI
)
GO

CREATE TABLE USERS (
	USERNAME NVARCHAR(100) PRIMARY KEY,
	PASSWORD NVARCHAR(100) NOT NULL,
	PERMISSION INT NOT NULL,				-- 0 : NHÂN VIÊN - 1 : QUẢN LÍ
	NAME_USER NVARCHAR(100) NOT NULL,
	EMAIL NCHAR(50) NOT NULL,
	PHONE INT NOT NULL
)
GO
CREATE TABLE DRINK_TYPE(
	ID_TYPE INT IDENTITY PRIMARY KEY,
	NAME_TYPE NVARCHAR(100) NOT NULL,
)

CREATE TABLE DRINK(
	ID_DRINK INT IDENTITY PRIMARY KEY,
	NAME_DRINK NVARCHAR(100) NOT NULL,
	ID_TYPE INT NOT NULL,
	PRICE FLOAT NOT NULL,
	ISDELETE BIT NOT NULL

	FOREIGN KEY (ID_TYPE) REFERENCES DBO.DRINK_TYPE(ID_TYPE)
)
GO

CREATE TABLE BILL(
	ID_BILL INT IDENTITY PRIMARY KEY,
	ORDERTIME DATE NOT NULL DEFAULT GETDATE(),
	ID_TABLE INT NOT NULL,
	IS_PAID INT NOT NULL DEFAULT 0, -- 0 : CHƯA THANH TOÁN , 1 : ĐÃ THANH TOÁN
	GRAND_TOTAL FLOAT NOT NULL 

	FOREIGN KEY (ID_TABLE) REFERENCES DBO.TABLE_DRINK(ID_TABLE)
)
GO

CREATE TABLE DETAIL_BILL(
	ID_BILL_DETAIL INT IDENTITY PRIMARY KEY,
	ID_BILL INT NOT NULL,
	ID_DRINK INT NOT NULL,
	QUANTITY INT NOT NULL DEFAULT 0,

	FOREIGN KEY (ID_BILL) REFERENCES DBO.BILL(ID_BILL),
	FOREIGN KEY (ID_DRINK) REFERENCES DBO.DRINK(ID_DRINK)
)

GO

CREATE PROC US_getUserByUserName
@userName nvarchar(100),@passWord NCHAR(100)
AS
BEGIN
	SELECT * FROM dbo.USERS WHERE USERNAME=@userName
END
GO

CREATE PROC US_Login
@userName NVARCHAR(100), @passWord NVARCHAR(100)
AS
BEGIN
	SELECT * FROM DBO.USERS WHERE USERNAME=@userName AND PASSWORD=@passWord
END
GO

CREATE PROC US_getTableList
AS SELECT * FROM dbo.TABLE_DRINK
GO

INSERT dbo.USERS
        ( USERNAME ,
          PASSWORD ,
          PERMISSION ,
          NAME_USER ,
          EMAIL ,
          PHONE
        )
VALUES  ( N'a1' , -- USERNAME - nvarchar(100)
          N'1' , -- PASSWORD - nvarchar(100)
          0 , -- PERMISSION - int
          N'' , -- NAME_USER - nvarchar(100)
          N'' , -- EMAIL - nchar(50)
          0  -- PHONE - int
        )


DECLARE @i INT =0
WHILE @i<=10
BEGIN
	INSERT dbo.TABLE_DRINK ( NAME_TABLE, STATUS ) VALUES  ( N'BÀN ' + CAST(@i AS NVARCHAR(100)), N'Trống' )
	SET @i=@i +1
END

GO


EXEC dbo.US_getTableList