CREATE DATABASE QUANLYTRASUA
GO

USE QUANLYTRASUA
GO


CREATE TABLE TABLE_DRINK(
	ID_TABLE INT IDENTITY PRIMARY KEY,
	NAME_TABLE NVARCHAR(100) NOT NULL,
	STATUS INT NOT NULL DEFAULT 0			-- 0 : TRỐNG - 1: CÓ NGƯỜI
)
GO

CREATE TABLE USERS (
	USERNAME NVARCHAR(100) PRIMARY KEY,
	PASSWORD NVARCHAR(100) NOT NULL,
	PERMISSION INT NOT NULL,				-- 0 : NHÂN VIÊN - 1 : QUẢN LÍ
	NAME_USER NVARCHAR(100) NOT NULL,
	EMAIL NCHAR(50) NOT NULL,
	PHONE INT NOT NULL
)
GO
CREATE TABLE DRINK_TYPE(
	ID_TYPE INT IDENTITY PRIMARY KEY,
	NAME_TYPE NVARCHAR(100) NOT NULL,
)

CREATE TABLE DRINK(
	ID_DRINK INT IDENTITY PRIMARY KEY,
	NAME_DRINK NVARCHAR(100) NOT NULL,
	ID_TYPE INT NOT NULL,
	PRICE FLOAT NOT NULL,
	ISDELETE BIT NOT NULL

	FOREIGN KEY (ID_TYPE) REFERENCES DBO.DRINK_TYPE(ID_TYPE)
)
GO

CREATE TABLE BILL(
	ID_BILL INT IDENTITY PRIMARY KEY,
	ORDERTIME DATE NOT NULL DEFAULT GETDATE(),
	ID_TABLE INT NOT NULL,
	IS_PAID INT NOT NULL DEFAULT 0, -- 0 : CHƯA THANH TOÁN , 1 : ĐÃ THANH TOÁN
	GRAND_TOTAL FLOAT NOT NULL 

	FOREIGN KEY (ID_TABLE) REFERENCES DBO.TABLE_DRINK(ID_TABLE)
)
GO

CREATE TABLE DETAIL_BILL(
	ID_BILL_DETAIL INT IDENTITY PRIMARY KEY,
	ID_BILL INT NOT NULL,
	ID_DRINK INT NOT NULL,
	QUANTITY INT NOT NULL DEFAULT 0,

	FOREIGN KEY (ID_BILL) REFERENCES DBO.BILL(ID_BILL),
	FOREIGN KEY (ID_DRINK) REFERENCES DBO.DRINK(ID_DRINK)
)
